config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public/homes#top"

  devise_for :customers
  #devise_for :customers,skip: [:passwords], controllers: {
    #registrations: "public/registrations",
    #sessions: 'public/sessions'
  #}
  devise_scope :customer do
    get "/customers", to: 'devise/registrations#new'
  end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admins/sessions"
  }


  resources :posts do
    resource :nices, only:[:create, :destroy], controller: 'public/nices'
  end

  namespace :admins do

    get '' => 'homes#top'
    resources :genres
    resources :customers
    resources :posts
    resources :comments, only: [:index, :destroy]
    get '/post_history' => 'post#post_history'
  end

  namespace :public do
    get '/about' => 'homes#about'
    post 'posts/create' => 'post#create', as: :post_create
    resources :genres
    resources :post do
      get :search, on: :collection
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :nices, only: [:index]
    get '/post_page' => 'post#post_page'
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe_confirm' => 'customers#unsubscribe_confirm'
    patch '/customers/unsubscribe' => 'customers#unsubscribe'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
         has_many :posts, dependent: :destroy
         has_many :nices, dependent: :destroy

has_many :nices, dependent: :destroy
has_many :likes, through: :nices, source: :post
has_many :comments, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/nice.rb
class Nice < ApplicationRecord
  

  
  belongs_to :customer
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  has_many :nices, dependent: :destroy
  has_many :likes, through: :nices, source: :customer
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true


def nices?(customer)
   nices.where(customer_id: customer.id).exists?
end

end

app/controllers/admins/comments_controller.rb
class Admins::CommentsController < ApplicationController

  def index
    redirect_to admins_post_path(params[:post_id])
  end

  def destroy
    comment = Comment.find(params[:id])
    @post = comment.post_id
    comment.destroy
    redirect_to admins_post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id], customer_id: current_customer.id)
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController

  def show
    @customer = Customer.find(params[:id])

  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admins_customer_path(params[:id])
  end

  private
  def customer_params
      params.require(:customer).permit(:nickname,:email,:encrypted_password,:like_list,:is_active)
  end

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
      if @genre.save
      redirect_to admins_genres_path
      else
      render :index
      end
  end

  def update
        @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    redirect_to admins_genres_path(@genre.id)
    else
   render :edit
    end
  end

private
def genre_params
      params.require(:genre).permit(:name)
end

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  def top
    @customers = Customer.all
  end
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def post_history
    @post = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admins_posts_path
  end

end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
#管理者
  def after_sign_in_path_for(resource)
    admins_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_sign_up_params,if: :devise_controller?

#会員
  def after_sign_in_path_for(resource)
    @customer = Customer.find_by(email: params[:customer][:email])
    if !@customer
      reset_session
    end
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @customer.valid_password?(params[:customer][:password])
      if !@customer.is_active
        reset_session
        new_customer_session_path
      else
        public_customers_mypage_path
      end
    end

  end
  def after_sign_out_path_for(resource)
    
    root_path
  end

   protected


  #If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
   end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/views/admins/genres/edit.html.erb
<h1>ジャンル編集</h1>
ジャンル名
<%= form_with model: @genre,url:admins_genre_path(@genre.id) do |f| %>
<%= f.text_field :name %></td>
<%= f.submit '変更を保存',class:"btn btn-success" %>
<% end %>

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="raw">
  <div class="box1">

<h1>ジャンル一覧・追加</h1>
<%= form_with model: Genre.new,url:admins_genres_path do |f| %>
ジャンル名
  <%= f.text_field :name %>
  <%= f.submit '新規登録',class:"btn btn-success" %>
<% end %>
      <h3>ジャンル</h3>
      <div>
      <% @genres.each do |genre| %>
        <%= genre.name %><br>
        <%= link_to "編集する",edit_admins_genre_path(genre.id),class:"btn btn-success" %><br>
      <% end %>
      </div>
      </div>
      </div>
      </div>

app/views/admins/posts/index.html.erb
<div class="container">
  <div class="box2">
<h1 style="text-align: center;">投稿一覧管理</h1>
<div class="box_in">
  <table class="table table-bordered">
<% @post.each do |posts| %><br>
<div class="box_on">
  <div class="justify-content: center;">
<tr><td style="color: white;"><%= link_to posts.title, admins_post_path(posts) %></td>
<td style="color: white;"><%= link_to "投稿削除", admins_post_path(posts.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "link_delete"%></td>
</div>
</div>
<% end %>
</table>
</div>

  </div>
</div>

app/views/admins/posts/post_history.html.erb
投稿履歴
<% @post.each do |p| %>
<%= p.title %>
<%= p.body %>
<% end %>

app/views/admins/posts/show.html.erb
<div class="container">
<div class="raw">
  <div class="box2">
<div style="text-align: center;">
<h1>投稿詳細管理</h1>
<div style="font-size: 50px;"><%= @post.title %></div>
<div style="font-size: 20px;"><%= @post.body %></div>

<% @comments.reverse.each do |comment| %>
<div class="comment_in">
  <div class="nickname">
<span><%= comment.customer.nickname %></span>
</div>
<div class="comment">
<%= comment.body %>
<%= link_to '削除', admins_comment_path(comment), method: :delete, class: "link_delete"%>
</div>
</div>
<% end %>
</div>
</div>
  </div>
</div>
</div>