config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "public/homes#top"

  devise_for :customers
  #devise_for :customers,skip: [:passwords], controllers: {
    #registrations: "public/registrations",
    #sessions: 'public/sessions'
  #}
  devise_scope :customer do
    get "/customers", to: 'devise/registrations#new'
  end


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admins, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admins/sessions"
  }


  resources :posts do
    resource :nices, only:[:create, :destroy], controller: 'public/nices'
  end

  namespace :admins do

    get '' => 'homes#top'
    resources :genres
    resources :customers
    resources :posts
    resources :comments, only: [:index, :destroy]
    get '/post_history' => 'post#post_history'
  end

  namespace :public do
    get '/about' => 'homes#about'
    post 'posts/create' => 'post#create', as: :post_create
    resources :genres
    resources :post do
      get :search, on: :collection
      resources :comments, only: [:index, :create, :destroy]
    end
    resources :nices, only: [:index]
    get '/post_page' => 'post#post_page'
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    patch '/customers/information' => 'customers#update'
    get '/customers/unsubscribe_confirm' => 'customers#unsubscribe_confirm'
    patch '/customers/unsubscribe' => 'customers#unsubscribe'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :customer
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
         has_many :posts, dependent: :destroy
         has_many :nices, dependent: :destroy

has_many :nices, dependent: :destroy
has_many :likes, through: :nices, source: :post
has_many :comments, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/nice.rb
class Nice < ApplicationRecord
  

  
  belongs_to :customer
  belongs_to :post
  
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :customer
  has_many :nices, dependent: :destroy
  has_many :likes, through: :nices, source: :customer
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true


def nices?(customer)
   nices.where(customer_id: customer.id).exists?
end

end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
      if @genre.save
      redirect_to admins_genres_path
      else
      render :index
      end
  end

  def update
        @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
    redirect_to admins_genres_path(@genre.id)
    else
   render :edit
    end
  end

private
def genre_params
      params.require(:genre).permit(:name)
end

end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  
  def top
    @customers = Customer.all
  end
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController

  def index
    @post = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
  end

  def post_history
    @post = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admins_posts_path
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_sign_up_params,if: :devise_controller?

#会員
  def after_sign_in_path_for(resource)
    @customer = Customer.find_by(email: params[:customer][:email])
    if !@customer
      reset_session
    end
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @customer.valid_password?(params[:customer][:password])
      if !@customer.is_active
        reset_session
        new_customer_session_path
      else
        public_customers_mypage_path
      end
    end

  end
  def after_sign_out_path_for(resource)
    
    root_path
  end

   protected


  #If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
   end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admins/comments_helper.rb
module Admins::CommentsHelper
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nices_helper.rb
module NicesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameCommunity</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<div class="wrapper">
    <header class="sticky-top",class= "background-color: #102a43 !important;">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
        <a>
          <%= link_to 'Game_Community', root_path, data: {"turbolinks" => false} %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to 'マイページ', public_customers_mypage_path,class: "btn btn-secondary"  %>
              </li>
              <li class="nav-item">
                <%= link_to '投稿一覧', public_post_index_path,class: "btn btn-secondary"  %>
              </li>
              <li class="nav-item">
                <%= link_to 'お気に入り一覧', public_nices_path,class: "btn btn-secondary" %>
              </li>
              <li class="nav-item">
                <%= link_to 'About', public_about_path,class: "btn btn-secondary" %>
              </li>

              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete,class: "btn btn-secondary" %>
              </li>
            <% elsif admin_signed_in? %>
            <%= link_to '投稿一覧', admins_posts_path,class: "btn btn-secondary" %>
            <%= link_to '会員一覧', admins_path,class: "btn btn-secondary" %>
            <%= link_to 'ジャンル一覧', admins_genres_path,class: "btn btn-secondary" %>
            <%= link_to 'About', public_about_path,class: "btn btn-secondary" %>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete,class: "btn btn-secondary" %>
            <% else %>
              <li class="nav-item">
                <%= link_to '投稿一覧', public_post_index_path,class: "btn btn-secondary" %>
              </li>
              <li class="nav-item">
                <%= link_to 'About', public_about_path,class: "btn btn-secondary" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path,class: "btn btn-secondary" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path,class: "btn btn-secondary"  %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

  <body>
    <%= yield %>
  </body>
   <footer>
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%#= image_tag('logo-white.png') %>
          </div>
          <div class="col-md-8">
            <ul class="p-0 list-unstyled">
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </div>
</html>